#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "forwardmotion.c"
#include "../../Libraries/Motors.h"
#include "../../Libraries/Servos.h"

task main()
{

	//waitForStart();
while(true){
	Motors_SetSpeed(S1, 1, 1, 20);
	Motors_SetSpeed(S1, 1, 2, -20);
	writeDebugStreamLine("%i | %i", Motors_GetPosition(S1, 1, 2), Motors_GetPosition(S1, 1, 1));
	//wait1Msec(60000);
}
}
