#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     ReflectiveLight, sensorLightActive)
#pragma config(Sensor, S4,     ActiveLight,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    SERVO_ARM,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    SERVO_CLAW,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int constrain(int x, int min, int max)
{
	if (x > max)
		return max;
	if (x < min)
		return min;
	return x;
}


int fixright(int joy)
{
	int motor = joy * (200/125);
	nxtDisplayString(4, "%i", motor);
	nxtDisplayString(5, "%i", joy);
	motor = motor - 100;
	return constrain(motor,-100,100);
}


int joymotor(int joy)
{
	int motor = joy*100 / 127;
	return constrain(motor,-100,100);
}

task main()
{
	//waitForStart();   // wait for start of tele-op phase
	int fowardyes = 0;
	int serv_claw = 100;
	int serv_arm = 100;

	while (true)
	{
		getJoystickSettings(joystick);
		//char sDest[100];
		//sprintf(sDest, "%d", ReflectiveLight);
		//nxtDisplayTextLine(0, sDest);

		//servo(SERVO_CLAW) = 100;
		//servo(SERVO_ARM) = 100;
		// read sensors
		//int sondis = SensorValue(S2);

		// Claw: Read buttons
		int claw_open = joy1Btn(3);
		int claw_close = joy1Btn(4);
		int arm_open = joy1Btn(1);
		int arm_close = joy1Btn(2);

    // Claw: decide what to do
		if (claw_open)
		{
			serv_claw = constrain(serv_claw + 10,20,255);
		}
		else if (claw_close)
		{
			serv_claw = constrain(serv_claw - 10,20,255);
		}
		if (arm_open)
		{
			serv_arm = constrain(serv_arm + 3,50,150);
		}
		else if (arm_close)
		{
			serv_arm = constrain(serv_arm - 6,50,150);
		}

		// Claw: set actuators
		servo(SERVO_CLAW) = serv_claw;
		servo(SERVO_ARM) = serv_arm;

		// Sensor: Read sensor
		if (SensorValue(S2) < 20)
		{
			fowardyes = 0;
		}
		else
		{
			fowardyes = 1;
		}

		// Sensor: If allowed move forward
		if (fowardyes == 0)
		{
			motor[motorD] = constrain(joymotor(joystick.joy1_y1), -100, 0);
			motor[motorE] = constrain(joymotor(joystick.joy1_y2), -100, 0);
			//nxtDisplayTextLine(3, constrain(fixright(joystick.joy1_y2), -100, 0));
			//eraseDisplay();
		}else
		{
			motor[motorD] = joymotor(joystick.joy1_y1);
			motor[motorE] = joystick.joy1_y2;
			nxtDisplayString(3, "%i", joystick.joy1_y2);
			//eraseDisplay();
		}

	  // sleep
		wait1Msec(33);
	}

}
