#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IROne,          sensorI2CCustom)
#pragma config(Sensor, S3,     IRTwo,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "movement.c"

// example.c

//float multiplier = 2.0; //This variable can account for different gear ratios between robots.
//17 for 1.0 forward on test bot
float mult = 0.58;
float turnmult = 1.9;
task main()
{
	//waitForStart();
	grabberUp();
	servo[servo2] = 30;
	forward(13.2*mult);
	forwardSlow(1.1);
	turnLSlow(0.2);
	forwardSuperSlow(1.1);
	grabberDown();
	wait1Msec(500);
	turnL(1.9*turnmult);
	//turnL(1.6); without left turn
	forward(2.3*mult);
	//turnL(1.1); without left turn
	turnL(1.1*turnmult);
	forward(14.1*mult);
	turnR(0.9*turnmult);
	forwardSuperSlow(2.1);
	//turnR(0.8);
	//forward(1.2*mult);
	/*turnR(0.3);
	forward(0.4*mult);
	turnR(0.1);
	forward(1.1*mult);
*/

}
