#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     IROne,          sensorI2CCustom)
#pragma config(Sensor, S3,     IRTwo,          sensorI2CCustom)
#pragma config(Sensor, S4,     sonarRight,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////
//TURN TEST//
/////////////


#include "JoystickDriver.c"
#include "movement.c"
#include "hitechnic-irseeker-v2.h"
// example.c

//float multiplier = 2.0; //This variable can account for different gear ratios between robots.
//17 for 1.0 forward on test bot

typedef struct
{
  int A;
  int B;
  int C;
  int D;
  int E;
} Values;


Values IR_TwoValue;

void IR_Update()
{
	//HTIRS2readAllACStrength(IROne, IR_OneValue.A, IR_OneValue.B, IR_OneValue.C, IR_OneValue.D, IR_OneValue.E);
	HTIRS2readAllACStrength(IRTwo, IR_TwoValue.A, IR_TwoValue.B, IR_TwoValue.C, IR_TwoValue.D, IR_TwoValue.E);
}

int checkpos(){

	if(SensorValue(sonarRight) >= 240)
	{
		return 2;
	}
	else
	{
		return 5;
	}
}

int checkIR(){
	IR_Update();
	if(IR_TwoValue.C > 20)
	{
		return 3;
	}
	else
	{
		return 1;
	}
}

void sonarSeek()
{
	while(SensorValue(sonarRight) >= 30){
		if(SensorValue(sonarRight) != 255)
		{
			forwardSlow(0.01);
		}
		else
		{
			//turnL(0.5);
			//while(SensorValue(sonarRight) >= 245)
			//{
			//	turnR(0.03);
			//}

		}

	}
	return;
}

task main()
{
	// Test loop

	//while(true)
	//{
	//	IR_Update();
	//	writeDebugStreamLine("IR: %i | Sonar: %i", IR_TwoValue.C, SensorValue(sonarRight));
	//	wait1Msec(500);
	//}
	//while(true){
	int pos = checkpos();
	if(pos == 2)
	{
		writeDebugStreamLine("2");
		turnL(1.5);
		forward(2.0);
		turnR(2.1);
		forward(1.7);
		sonarSeek();

	}
	else
	{
		int posIR = checkIR();
		if (posIR == 1)
		{
			writeDebugStreamLine("1");
			turnL(2.0);
			forward(2.0);
			turnR(2.0);
			forward(4.0);
			turnR(2.0);
			forward(3.0);
			sonarSeek();
		}
		else
		{
			writeDebugStreamLine("3");
			forward(1.5);
			sonarSeek();
		}



//	wait1Msec(1000);
	//turnR(2.0);
	//motor[motorA] = 100;
	//wait10Msec(100);
//}
}
}
